// models/ProductCode.js
import mongoose from "mongoose";

const ProductCodeSchema = new mongoose.Schema(
  {
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
      index: true,
    },

    sku: { type: String, required: true },

    barcode: {
      value: { type: String, required: true },
      format: { type: String, default: "CODE128" }, // Zoho-style
    },

    qr: {
      value: { type: String, required: true },
      version: { type: Number, default: 1 },
    },

    autoGenerated: { type: Boolean, default: true },

    status: {
      type: String,
      enum: ["active", "disabled"],
      default: "active",
    },
  },
  { timestamps: true }
);

export default mongoose.model("ProductCode", ProductCodeSchema);
